# Generated by Django 3.2.3 on 2021-06-26 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210626_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placed',
            name='date',
        ),
    ]
