# Generated by Django 3.2.3 on 2021-06-26 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_placed_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reqq',
            name='Customer',
        ),
        migrations.RemoveField(
            model_name='reqq',
            name='user',
        ),
    ]
